"""Rider mobile compat router — /api/v1/rider/kyc + /api/v1/rider/scan/parcel.

These are the contracts the rider mobile app SDK calls directly. Wired
2026-05-29 to match the SDK shape generated by the customer/rider
app code-gen step.

Routes:

    GET  /rider/kyc                  — current rider KYC row (404 if none)
    POST /rider/kyc                  — submit / re-submit
    POST /rider/kyc/upload           — multipart photo upload, returns {url}
    POST /rider/scan/parcel          — bridge to deliveries scan_verify
                                       (resolves stop_id → assignment, calls
                                       existing DeliveryService.scan_verify
                                       with intent='delivery')
"""
from __future__ import annotations

from typing import Annotated, Any
from uuid import UUID

from fastapi import APIRouter, Depends, File, HTTPException, UploadFile
from pydantic import Field
from sqlalchemy import select

from app.core.db.uow import UnitOfWork, get_uow
from app.core.logging import get_logger
from app.core.security.deps import get_current_principal
from app.core.security.principal import Principal
from app.core.security.rbac import requires_permission
from app.core.validation import StrictModel
from app.modules.iam.permissions import P_RIDER_APP
from app.modules.rider_kyc.models import RiderKycSubmission
from app.modules.rider_kyc.service import (
    get_for_user,
    store_kyc_file,
    upsert_for_user,
)

_log = get_logger("hypershop.rider_kyc")

router = APIRouter(prefix="/rider", tags=["rider-mobile-compat"])


# ============================================================
#  Schemas — match rider-android/rider-hms SDK contracts
# ============================================================
class RiderKycSubmitIn(StrictModel):
    full_name: str = Field(min_length=1, max_length=160)
    profile_photo_url: str | None = None
    nid_number: str | None = Field(default=None, max_length=32)
    nid_front_url: str | None = None
    nid_back_url: str | None = None
    mobile_primary: str = Field(min_length=1, max_length=32)
    mobile_secondary: str | None = Field(default=None, max_length=32)
    house_no: str | None = Field(default=None, max_length=64)
    flat_no: str | None = Field(default=None, max_length=32)
    area: str | None = Field(default=None, max_length=160)
    lat: float | None = None
    lng: float | None = None
    reference_name: str | None = Field(default=None, max_length=160)
    reference_nid: str | None = Field(default=None, max_length=32)
    reference_mobile: str | None = Field(default=None, max_length=32)


class RiderKycWire(StrictModel):
    id: str
    user_id: str
    full_name: str
    profile_photo_url: str | None = None
    nid_number: str | None = None
    nid_front_url: str | None = None
    nid_back_url: str | None = None
    mobile_primary: str
    mobile_secondary: str | None = None
    house_no: str | None = None
    flat_no: str | None = None
    area: str | None = None
    lat: float | None = None
    lng: float | None = None
    reference_name: str | None = None
    reference_nid: str | None = None
    reference_mobile: str | None = None
    status: str
    rejection_reason: str | None = None
    submitted_at: str | None = None
    reviewed_at: str | None = None


class KycUploadOut(StrictModel):
    url: str


class ParcelScanIn(StrictModel):
    stop_id: str = Field(min_length=1, max_length=80)
    qr_code: str = Field(min_length=1, max_length=128)
    lat: float | None = None
    lng: float | None = None


class ParcelScanOut(StrictModel):
    ok: bool
    stop_id: str
    qr_code: str
    parcel_id: str | None = None
    order_id: str | None = None
    message: str | None = None


def _to_wire(row: RiderKycSubmission) -> RiderKycWire:
    return RiderKycWire(
        id=str(row.id),
        user_id=str(row.user_id),
        full_name=row.full_name,
        profile_photo_url=row.profile_photo_url,
        nid_number=row.nid_number,
        nid_front_url=row.nid_front_url,
        nid_back_url=row.nid_back_url,
        mobile_primary=row.mobile_primary,
        mobile_secondary=row.mobile_secondary,
        house_no=row.house_no,
        flat_no=row.flat_no,
        area=row.area,
        lat=row.lat,
        lng=row.lng,
        reference_name=row.reference_name,
        reference_nid=row.reference_nid,
        reference_mobile=row.reference_mobile,
        status=row.status,
        rejection_reason=row.rejection_reason,
        submitted_at=row.submitted_at.isoformat() if row.submitted_at else None,
        reviewed_at=row.reviewed_at.isoformat() if row.reviewed_at else None,
    )


# ============================================================
#  KYC endpoints
# ============================================================
@router.get(
    "/kyc",
    response_model=RiderKycWire,
    summary="Get the current rider's KYC submission (404 if none)",
    dependencies=[Depends(requires_permission(P_RIDER_APP))],
)
async def get_my_kyc(
    principal: Annotated[Principal, Depends(get_current_principal)],
    uow: Annotated[UnitOfWork, Depends(get_uow)],
) -> RiderKycWire:
    async with uow as u:
        row = await get_for_user(u.session, principal.user_id)
    if row is None:
        raise HTTPException(status_code=404, detail={
            "code": "kyc_not_submitted",
            "message": "No KYC submission found for this rider.",
        })
    return _to_wire(row)


@router.post(
    "/kyc",
    response_model=RiderKycWire,
    status_code=201,
    summary="Submit or re-submit the current rider's KYC",
    description=(
        "Re-submission resets ``status`` back to ``pending`` and clears "
        "any previous ``rejection_reason``. Hub admin reviews at "
        "``/admin/rider-kyc`` (admin queue endpoint TBD)."
    ),
    dependencies=[Depends(requires_permission(P_RIDER_APP))],
)
async def submit_my_kyc(
    body: RiderKycSubmitIn,
    principal: Annotated[Principal, Depends(get_current_principal)],
    uow: Annotated[UnitOfWork, Depends(get_uow)],
) -> RiderKycWire:
    async with uow.transactional() as session:
        row = await upsert_for_user(
            session,
            user_id=principal.user_id,
            fields=body.model_dump(exclude_unset=False),
        )
    return _to_wire(row)


@router.post(
    "/kyc/upload",
    response_model=KycUploadOut,
    summary="Upload a KYC photo (profile / NID front / NID back)",
    description=(
        "Multipart upload. Returns ``{\"url\": ...}``; the rider app then "
        "passes that URL back as ``profile_photo_url`` / ``nid_front_url`` "
        "/ ``nid_back_url`` in the POST ``/rider/kyc`` body. Splitting "
        "upload from submit keeps re-tries idempotent — a network drop on "
        "one photo doesn't lose the other two."
    ),
    dependencies=[Depends(requires_permission(P_RIDER_APP))],
)
async def upload_kyc_photo(
    file: Annotated[UploadFile, File()],
    principal: Annotated[Principal, Depends(get_current_principal)],
) -> KycUploadOut:
    try:
        url = await store_kyc_file(file, user_id=principal.user_id, kind="kyc")
    except ValueError as e:
        raise HTTPException(status_code=422, detail={
            "code": "invalid_upload", "message": str(e),
        })
    except Exception as e:  # noqa: BLE001 — surface to client cleanly
        _log.exception("rider_kyc_upload_failed", error=str(e))
        raise HTTPException(status_code=500, detail={
            "code": "upload_failed", "message": "KYC photo upload failed.",
        })
    return KycUploadOut(url=url)


# ============================================================
#  Parcel scan bridge — /rider/scan/parcel
# ============================================================
@router.post(
    "/scan/parcel",
    response_model=ParcelScanOut,
    summary="Verify a scanned parcel QR against the stop's assigned order",
    description=(
        "Bridge to the existing ``DeliveryService.scan_verify`` flow but "
        "scoped by ``stop_id`` (what the rider mobile app's QrScanScreen "
        "knows) instead of ``assignment_id`` (what the deliveries router "
        "expects). The bridge resolves stop → run-sheet stop → assignment "
        "and calls scan_verify with ``intent='delivery'``."
    ),
    dependencies=[Depends(requires_permission(P_RIDER_APP))],
)
async def scan_parcel(
    body: ParcelScanIn,
    principal: Annotated[Principal, Depends(get_current_principal)],
    uow: Annotated[UnitOfWork, Depends(get_uow)],
) -> ParcelScanOut:
    # Lazy import to avoid circulars at module-load time.
    from app.modules.deliveries.service import DeliveryService
    from app.modules.rider_routing.models import RunSheetStop

    async with uow.transactional() as session:
        # Resolve stop_id → delivery_assignment_id
        try:
            stop_uuid = UUID(body.stop_id)
        except ValueError:
            return ParcelScanOut(
                ok=False, stop_id=body.stop_id, qr_code=body.qr_code,
                message="invalid stop_id format (expected UUID)",
            )
        stop = (await session.execute(
            select(RunSheetStop).where(RunSheetStop.id == stop_uuid)
        )).scalar_one_or_none()
        if stop is None or stop.delivery_assignment_id is None:
            return ParcelScanOut(
                ok=False, stop_id=body.stop_id, qr_code=body.qr_code,
                message="stop not found or has no assigned delivery",
            )

        svc = DeliveryService(session)
        rider = await svc.rider_for_user(principal.user_id)
        result = await svc.scan_verify(
            principal=principal,
            rider=rider,
            assignment_id=stop.delivery_assignment_id,
            scanned_code=body.qr_code,
            intent="delivery",
        )

    return ParcelScanOut(
        ok=bool(result.get("ok")),
        stop_id=body.stop_id,
        qr_code=body.qr_code,
        order_id=result.get("expected_code"),
        message=None if result.get("ok") else "barcode does not match order code",
    )


__all__ = ["router"]
