"""0058 seo_agents — M34 SEO module gains AI-driven SEO automation.

Adds six tables that back the new ``app/modules/seo/agents/`` sub-module:

  seo_agent_keywords        — tracked keywords + priority + target_url
  seo_agent_tasks           — approval-gated work generated by agents
  seo_agent_runs            — per-execution audit log (input + output JSON)
  seo_agent_rank_snapshots  — point-in-time rank tracking rows
  seo_agent_page_audits     — technical audit rows (issues + recommendations)
  seo_agent_approval_logs   — approve/reject decisions on tasks

All names are prefixed ``seo_agent_*`` to keep them separate from the
pre-existing seo_meta_overrides / seo_meta_translations / seo_url_redirects /
homepage_banners / blog_posts tables from earlier M34 sprints.

The source code originated in a separate "seo_agents" sandbox; this
migration ports the schema with two adaptations for Hypershop:
  - UUID primary keys (instead of integer autoincrement) to match the
    rest of the codebase
  - All timestamp columns use timezone-aware DateTime + ``now()`` server
    defaults to match the Hypershop pattern
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB, UUID

revision: str = "0058_seo_agents"
down_revision: str | Sequence[str] | None = "0057_seo_translations"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ---------------- seo_agent_keywords ----------------
    op.create_table(
        "seo_agent_keywords",
        sa.Column("id", UUID(as_uuid=True), primary_key=True,
                  server_default=sa.text("gen_random_uuid()")),
        sa.Column("keyword", sa.String(255), nullable=False),
        sa.Column("target_location", sa.String(120),
                  nullable=False, server_default="Bangladesh"),
        sa.Column("priority", sa.String(30),
                  nullable=False, server_default="medium"),
        sa.Column("keyword_type", sa.String(50), nullable=True),
        sa.Column("target_url", sa.String(500), nullable=True),
        sa.Column("status", sa.String(30),
                  nullable=False, server_default="new"),
        sa.Column("created_by", UUID(as_uuid=True),
                  sa.ForeignKey("users.id", ondelete="SET NULL"),
                  nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint(
            "priority IN ('low','medium','high','urgent')",
            name="ck_seo_agent_keywords_priority_enum",
        ),
        sa.CheckConstraint(
            "status IN ('new','analyzed','optimizing','ranking','paused')",
            name="ck_seo_agent_keywords_status_enum",
        ),
    )
    op.create_index(
        "ix_seo_agent_keywords_status_priority",
        "seo_agent_keywords", ["status", "priority"],
    )
    op.create_index(
        "ix_seo_agent_keywords_keyword",
        "seo_agent_keywords", ["keyword"],
    )

    # ---------------- seo_agent_tasks ----------------
    op.create_table(
        "seo_agent_tasks",
        sa.Column("id", UUID(as_uuid=True), primary_key=True,
                  server_default=sa.text("gen_random_uuid()")),
        sa.Column("keyword_id", UUID(as_uuid=True),
                  sa.ForeignKey("seo_agent_keywords.id", ondelete="SET NULL"),
                  nullable=True),
        sa.Column("task_type", sa.String(80), nullable=False),
        sa.Column("title", sa.String(255), nullable=False),
        sa.Column("description", sa.Text, nullable=False),
        sa.Column("payload", JSONB, nullable=False,
                  server_default=sa.text("'{}'::jsonb")),
        sa.Column("priority", sa.String(30),
                  nullable=False, server_default="medium"),
        sa.Column("status", sa.String(30),
                  nullable=False, server_default="pending_approval"),
        sa.Column("approved_by", UUID(as_uuid=True),
                  sa.ForeignKey("users.id", ondelete="SET NULL"),
                  nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint(
            "status IN ('pending_approval','approved','rejected','completed')",
            name="ck_seo_agent_tasks_status_enum",
        ),
        sa.CheckConstraint(
            "priority IN ('low','medium','high','urgent')",
            name="ck_seo_agent_tasks_priority_enum",
        ),
    )
    op.create_index(
        "ix_seo_agent_tasks_status_priority",
        "seo_agent_tasks", ["status", "priority"],
    )
    op.create_index(
        "ix_seo_agent_tasks_keyword",
        "seo_agent_tasks", ["keyword_id"],
    )

    # ---------------- seo_agent_runs ----------------
    op.create_table(
        "seo_agent_runs",
        sa.Column("id", UUID(as_uuid=True), primary_key=True,
                  server_default=sa.text("gen_random_uuid()")),
        sa.Column("agent_name", sa.String(100), nullable=False),
        sa.Column("keyword_id", UUID(as_uuid=True),
                  sa.ForeignKey("seo_agent_keywords.id", ondelete="SET NULL"),
                  nullable=True),
        sa.Column("input_payload", JSONB,
                  nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("output_payload", JSONB,
                  nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("status", sa.String(30),
                  nullable=False, server_default="success"),
        sa.Column("error", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint(
            "status IN ('success','partial','error')",
            name="ck_seo_agent_runs_status_enum",
        ),
    )
    op.create_index(
        "ix_seo_agent_runs_keyword_created",
        "seo_agent_runs", ["keyword_id", "created_at"],
    )

    # ---------------- seo_agent_rank_snapshots ----------------
    op.create_table(
        "seo_agent_rank_snapshots",
        sa.Column("id", UUID(as_uuid=True), primary_key=True,
                  server_default=sa.text("gen_random_uuid()")),
        sa.Column("keyword_id", UUID(as_uuid=True),
                  sa.ForeignKey("seo_agent_keywords.id", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("target_url", sa.String(500), nullable=True),
        sa.Column("position", sa.Integer, nullable=True),
        sa.Column("location", sa.String(120),
                  nullable=False, server_default="Bangladesh"),
        sa.Column("device", sa.String(30),
                  nullable=False, server_default="mobile"),
        sa.Column("impressions", sa.Integer, nullable=True),
        sa.Column("clicks", sa.Integer, nullable=True),
        sa.Column("ctr", sa.Float, nullable=True),
        sa.Column("source", sa.String(80),
                  nullable=False, server_default="manual_or_api"),
        sa.Column("captured_at", sa.DateTime(timezone=True),
                  nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint(
            "device IN ('mobile','desktop','tablet')",
            name="ck_seo_agent_rank_device_enum",
        ),
        sa.CheckConstraint(
            "position IS NULL OR position >= 1",
            name="ck_seo_agent_rank_position_min",
        ),
    )
    op.create_index(
        "ix_seo_agent_rank_keyword_captured",
        "seo_agent_rank_snapshots", ["keyword_id", "captured_at"],
    )

    # ---------------- seo_agent_page_audits ----------------
    op.create_table(
        "seo_agent_page_audits",
        sa.Column("id", UUID(as_uuid=True), primary_key=True,
                  server_default=sa.text("gen_random_uuid()")),
        sa.Column("url", sa.String(500), nullable=False),
        sa.Column("score", sa.Integer, nullable=False),
        sa.Column("issues", JSONB,
                  nullable=False, server_default=sa.text("'[]'::jsonb")),
        sa.Column("recommendations", JSONB,
                  nullable=False, server_default=sa.text("'[]'::jsonb")),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint(
            "score >= 0 AND score <= 100",
            name="ck_seo_agent_audits_score_range",
        ),
    )
    op.create_index(
        "ix_seo_agent_audits_url_created",
        "seo_agent_page_audits", ["url", "created_at"],
    )

    # ---------------- seo_agent_approval_logs ----------------
    op.create_table(
        "seo_agent_approval_logs",
        sa.Column("id", UUID(as_uuid=True), primary_key=True,
                  server_default=sa.text("gen_random_uuid()")),
        sa.Column("task_id", UUID(as_uuid=True),
                  sa.ForeignKey("seo_agent_tasks.id", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("action", sa.String(30), nullable=False),
        sa.Column("actor_id", UUID(as_uuid=True),
                  sa.ForeignKey("users.id", ondelete="SET NULL"),
                  nullable=True),
        sa.Column("comment", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  nullable=False, server_default=sa.func.now()),
        sa.CheckConstraint(
            "action IN ('approved','rejected')",
            name="ck_seo_agent_approval_action_enum",
        ),
    )
    op.create_index(
        "ix_seo_agent_approval_task_created",
        "seo_agent_approval_logs", ["task_id", "created_at"],
    )


def downgrade() -> None:
    op.drop_index(
        "ix_seo_agent_approval_task_created",
        table_name="seo_agent_approval_logs",
    )
    op.drop_table("seo_agent_approval_logs")
    op.drop_index(
        "ix_seo_agent_audits_url_created",
        table_name="seo_agent_page_audits",
    )
    op.drop_table("seo_agent_page_audits")
    op.drop_index(
        "ix_seo_agent_rank_keyword_captured",
        table_name="seo_agent_rank_snapshots",
    )
    op.drop_table("seo_agent_rank_snapshots")
    op.drop_index(
        "ix_seo_agent_runs_keyword_created",
        table_name="seo_agent_runs",
    )
    op.drop_table("seo_agent_runs")
    op.drop_index(
        "ix_seo_agent_tasks_keyword",
        table_name="seo_agent_tasks",
    )
    op.drop_index(
        "ix_seo_agent_tasks_status_priority",
        table_name="seo_agent_tasks",
    )
    op.drop_table("seo_agent_tasks")
    op.drop_index(
        "ix_seo_agent_keywords_keyword",
        table_name="seo_agent_keywords",
    )
    op.drop_index(
        "ix_seo_agent_keywords_status_priority",
        table_name="seo_agent_keywords",
    )
    op.drop_table("seo_agent_keywords")
