"""ORM models for the SEO agents sub-module.

Six tables, all created in migration 0058_seo_agents:

  seo_agent_keywords        — tracked keywords + target location + priority
  seo_agent_tasks           — approval-gated work generated by agents
  seo_agent_runs            — per-execution audit log (input + output JSON)
  seo_agent_rank_snapshots  — point-in-time rank tracking rows
  seo_agent_page_audits     — technical audit rows (issues + recommendations)
  seo_agent_approval_logs   — approval/reject decisions on tasks

Names are prefixed ``seo_agent_*`` to keep the existing seo_meta_* and
seo_url_redirects tables (M34 base) separate from this AI layer.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any
from uuid import UUID

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.core.db.base import Base
from app.core.db.mixins import TimestampMixin


# ============================================================
#  seo_agent_keywords
# ============================================================
class SeoAgentKeyword(Base, TimestampMixin):
    """A keyword the SEO team is tracking + optimizing for."""

    __tablename__ = "seo_agent_keywords"

    id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    keyword: Mapped[str] = mapped_column(String(255), nullable=False)
    target_location: Mapped[str] = mapped_column(
        String(120), nullable=False, server_default="Bangladesh",
    )
    # SeoAgentPriority enum.
    priority: Mapped[str] = mapped_column(
        String(30), nullable=False, server_default="medium",
    )
    # Free-form classification (e.g. "informational", "transactional",
    # "navigational"). Optional — agents fill this on first analyse.
    keyword_type: Mapped[str | None] = mapped_column(
        String(50), nullable=True,
    )
    target_url: Mapped[str | None] = mapped_column(
        String(500), nullable=True,
    )
    # SeoAgentKeywordStatus enum.
    status: Mapped[str] = mapped_column(
        String(30), nullable=False, server_default="new",
    )
    created_by: Mapped[UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )

    __table_args__ = (
        CheckConstraint(
            "priority IN ('low','medium','high','urgent')",
            name="ck_seo_agent_keywords_priority_enum",
        ),
        CheckConstraint(
            "status IN ('new','analyzed','optimizing','ranking','paused')",
            name="ck_seo_agent_keywords_status_enum",
        ),
        Index(
            "ix_seo_agent_keywords_status_priority",
            "status", "priority",
        ),
        Index(
            "ix_seo_agent_keywords_keyword",
            "keyword",
        ),
    )


# ============================================================
#  seo_agent_tasks
# ============================================================
class SeoAgentTask(Base):
    """An approval-gated piece of work generated by an agent run.

    Tasks are NEVER auto-executed — operators review the payload and
    decide approve/reject. Approval writes a row in
    ``seo_agent_approval_logs`` for traceability.
    """

    __tablename__ = "seo_agent_tasks"

    id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    keyword_id: Mapped[UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("seo_agent_keywords.id", ondelete="SET NULL"),
        nullable=True,
    )
    # SeoAgentTaskType enum.
    task_type: Mapped[str] = mapped_column(String(80), nullable=False)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    payload: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb"),
    )
    priority: Mapped[str] = mapped_column(
        String(30), nullable=False, server_default="medium",
    )
    # SeoAgentTaskStatus enum.
    status: Mapped[str] = mapped_column(
        String(30), nullable=False, server_default="pending_approval",
    )
    approved_by: Mapped[UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    approved_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
    )

    __table_args__ = (
        CheckConstraint(
            "status IN ('pending_approval','approved','rejected','completed')",
            name="ck_seo_agent_tasks_status_enum",
        ),
        CheckConstraint(
            "priority IN ('low','medium','high','urgent')",
            name="ck_seo_agent_tasks_priority_enum",
        ),
        Index(
            "ix_seo_agent_tasks_status_priority",
            "status", "priority",
        ),
        Index(
            "ix_seo_agent_tasks_keyword",
            "keyword_id",
        ),
    )


# ============================================================
#  seo_agent_runs
# ============================================================
class SeoAgentRun(Base):
    """Per-execution audit log row.

    Captures the input payload, output payload, and success/error status
    of every agent run. Operators inspect this to debug fallback paths
    when ``OPENAI_API_KEY`` is unset (or when the API errors).
    """

    __tablename__ = "seo_agent_runs"

    id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    agent_name: Mapped[str] = mapped_column(String(100), nullable=False)
    keyword_id: Mapped[UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("seo_agent_keywords.id", ondelete="SET NULL"),
        nullable=True,
    )
    input_payload: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb"),
    )
    output_payload: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb"),
    )
    status: Mapped[str] = mapped_column(
        String(30), nullable=False, server_default="success",
    )
    error: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
    )

    __table_args__ = (
        CheckConstraint(
            "status IN ('success','partial','error')",
            name="ck_seo_agent_runs_status_enum",
        ),
        Index(
            "ix_seo_agent_runs_keyword_created",
            "keyword_id", "created_at",
        ),
    )


# ============================================================
#  seo_agent_rank_snapshots
# ============================================================
class SeoAgentRankSnapshot(Base):
    """Point-in-time rank tracking row.

    Imported from operator paste / external rank-tracking API (GSC,
    SerpAPI, etc.). The service treats every row as immutable — never
    update / delete; build a new snapshot for new data.
    """

    __tablename__ = "seo_agent_rank_snapshots"

    id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    keyword_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("seo_agent_keywords.id", ondelete="CASCADE"),
        nullable=False,
    )
    target_url: Mapped[str | None] = mapped_column(
        String(500), nullable=True,
    )
    position: Mapped[int | None] = mapped_column(Integer, nullable=True)
    location: Mapped[str] = mapped_column(
        String(120), nullable=False, server_default="Bangladesh",
    )
    device: Mapped[str] = mapped_column(
        String(30), nullable=False, server_default="mobile",
    )
    impressions: Mapped[int | None] = mapped_column(Integer, nullable=True)
    clicks: Mapped[int | None] = mapped_column(Integer, nullable=True)
    ctr: Mapped[float | None] = mapped_column(Float, nullable=True)
    source: Mapped[str] = mapped_column(
        String(80), nullable=False, server_default="manual_or_api",
    )
    captured_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
    )

    __table_args__ = (
        CheckConstraint(
            "device IN ('mobile','desktop','tablet')",
            name="ck_seo_agent_rank_device_enum",
        ),
        CheckConstraint(
            "position IS NULL OR position >= 1",
            name="ck_seo_agent_rank_position_min",
        ),
        Index(
            "ix_seo_agent_rank_keyword_captured",
            "keyword_id", "captured_at",
        ),
    )


# ============================================================
#  seo_agent_page_audits
# ============================================================
class SeoAgentPageAudit(Base):
    """Technical audit of a single URL.

    A score 0-100 derived from HTML inspection (title, meta description,
    canonical, JSON-LD). When ``html`` is not provided, the audit row is
    written with a placeholder score (70) and ``html_not_provided``
    issue — operators integrate a crawler for real audits.
    """

    __tablename__ = "seo_agent_page_audits"

    id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    url: Mapped[str] = mapped_column(String(500), nullable=False)
    score: Mapped[int] = mapped_column(Integer, nullable=False)
    issues: Mapped[list[dict[str, Any]]] = mapped_column(
        JSONB, nullable=False, server_default=text("'[]'::jsonb"),
    )
    recommendations: Mapped[list[dict[str, Any]]] = mapped_column(
        JSONB, nullable=False, server_default=text("'[]'::jsonb"),
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
    )

    __table_args__ = (
        CheckConstraint(
            "score >= 0 AND score <= 100",
            name="ck_seo_agent_audits_score_range",
        ),
        Index(
            "ix_seo_agent_audits_url_created",
            "url", "created_at",
        ),
    )


# ============================================================
#  seo_agent_approval_logs
# ============================================================
class SeoAgentApprovalLog(Base):
    """Audit trail of approve/reject decisions on tasks."""

    __tablename__ = "seo_agent_approval_logs"

    id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    task_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("seo_agent_tasks.id", ondelete="CASCADE"),
        nullable=False,
    )
    action: Mapped[str] = mapped_column(String(30), nullable=False)
    actor_id: Mapped[UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    comment: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
    )

    __table_args__ = (
        CheckConstraint(
            "action IN ('approved','rejected')",
            name="ck_seo_agent_approval_action_enum",
        ),
        Index(
            "ix_seo_agent_approval_task_created",
            "task_id", "created_at",
        ),
    )
