"""Sprint 5 parity-tier routes for Module 47 — Customer Care.

12 of 15 items close cleanly here. The 3 deferred are documented in
the v8 changelog (pgvector, frontend i18n, PDF transcript export).
"""
from __future__ import annotations

import csv
import io
import time
from collections import deque
from datetime import datetime, time as dtime, timezone
from typing import Annotated, Any
from uuid import UUID

from fastapi import APIRouter, Depends, File, HTTPException, Path, Query, UploadFile, status
from fastapi.responses import StreamingResponse
from pydantic import Field
from sqlalchemy import desc, select, text as _t

from app.core.audit.service import record_audit
from app.core.db.uow import UnitOfWork, get_uow
from app.core.errors import NotFoundError, ValidationError
from app.core.logging import get_logger
from app.core.security.deps import get_current_principal
from app.core.security.principal import Principal
from app.core.security.rbac import requires_permission
from app.core.validation import StrictModel
from app.modules.customer_care.config import settings as cc_settings
from app.modules.customer_care.models import (
    CCConversation,
    CCKnowledgeDocument,
)

_AGENT = "customercare.agent"
_ADMIN = "customercare.admin"
_RAG_ADMIN = "customercare.rag.admin"

router = APIRouter(tags=["customer-care-sprint5"])
_log = get_logger("hypershop.customer_care.sprint5")


# ============================================================== Bulk KB CSV
@router.post(
    "/kb/import-csv",
    summary="Bulk-ingest KB documents from CSV (columns: title, body[, language, source_url])",
    dependencies=[Depends(requires_permission(_RAG_ADMIN))],
)
async def kb_import_csv(
    uow: Annotated[UnitOfWork, Depends(get_uow)],
    principal: Annotated[Principal, Depends(get_current_principal)],
    file: UploadFile = File(...),
) -> dict[str, Any]:
    raw = await file.read()
    if len(raw) > 2 * 1024 * 1024:
        raise ValidationError("CSV too large — 2 MB max")
    try:
        text_str = raw.decode("utf-8", errors="replace")
    except Exception:
        raise ValidationError("CSV must be UTF-8")
    reader = csv.DictReader(io.StringIO(text_str))
    rows = list(reader)
    if not rows:
        raise ValidationError("CSV is empty or missing header row")
    # Reuse the KB ingest flow inline (chunk + sync embedding via worker)
    from app.modules.customer_care.api.kb_csat import _simple_chunk
    import hashlib
    from sqlalchemy.dialects.postgresql import insert as _pg_insert
    from app.modules.customer_care.models import CCKnowledgeChunk
    ingested = 0
    skipped_dup = 0
    skipped_invalid = 0
    async with uow.transactional() as session:
        for r in rows:
            title = (r.get("title") or "").strip()
            body = (r.get("body") or "").strip()
            if not title or not body:
                skipped_invalid += 1
                continue
            digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
            dup = (
                await session.execute(
                    select(CCKnowledgeDocument).where(
                        CCKnowledgeDocument.body_sha256 == digest,
                        CCKnowledgeDocument.is_active.is_(True),
                    )
                )
            ).scalar_one_or_none()
            if dup:
                skipped_dup += 1
                continue
            doc = CCKnowledgeDocument(
                title=title[:255], body=body, body_sha256=digest,
                source_type=(r.get("source_type") or "text")[:40],
                source_url=(r.get("source_url") or None),
                language=(r.get("language") or None),
            )
            session.add(doc)
            await session.flush()
            chunks = _simple_chunk(body)
            for i, ch in enumerate(chunks):
                session.add(
                    CCKnowledgeChunk(
                        document_id=doc.id, position=i,
                        text_body=ch,
                        text_hash=hashlib.sha256(ch.encode("utf-8")).hexdigest(),
                        token_count=len(ch) // 4,
                    )
                )
            doc.chunk_count = len(chunks)
            doc.indexed_at = datetime.now(timezone.utc)
            ingested += 1
        await record_audit(
            actor=principal,
            action="customer_care.kb.bulk_import",
            resource_type="cc_knowledge_documents",
            metadata={
                "ingested": ingested,
                "skipped_dup": skipped_dup,
                "skipped_invalid": skipped_invalid,
            },
        )
    return {
        "ingested": ingested,
        "skipped_duplicates": skipped_dup,
        "skipped_invalid": skipped_invalid,
        "total_rows": len(rows),
        "note": "Embeddings will be generated by the cc_kb_embed_worker cron",
    }


# ============================================================== KB doc update
class KbDocPatch(StrictModel):
    title: str | None = Field(default=None, min_length=1, max_length=255)
    body: str | None = Field(default=None, min_length=1, max_length=200_000)
    is_active: bool | None = None
    language: str | None = Field(default=None, max_length=8)


@router.patch(
    "/kb/documents/{doc_id}",
    summary="Update a KB document (re-chunks + clears stale embeddings if body changes)",
    dependencies=[Depends(requires_permission(_RAG_ADMIN))],
)
async def kb_patch(
    doc_id: Annotated[UUID, Path(...)],
    body: KbDocPatch,
    uow: Annotated[UnitOfWork, Depends(get_uow)],
    principal: Annotated[Principal, Depends(get_current_principal)],
) -> dict[str, Any]:
    fields = body.model_dump(exclude_none=True)
    if not fields:
        raise ValidationError("at least one field must be provided")
    import hashlib
    from app.modules.customer_care.api.kb_csat import _simple_chunk
    from app.modules.customer_care.models import CCKnowledgeChunk
    async with uow.transactional() as session:
        doc = (
            await session.execute(
                select(CCKnowledgeDocument).where(CCKnowledgeDocument.id == doc_id)
            )
        ).scalar_one_or_none()
        if doc is None:
            raise NotFoundError("KB doc not found")
        body_changed = False
        if "body" in fields:
            new_body = fields["body"]
            new_digest = hashlib.sha256(new_body.encode("utf-8")).hexdigest()
            if new_digest != doc.body_sha256:
                doc.body = new_body
                doc.body_sha256 = new_digest
                body_changed = True
        for k in ("title", "is_active", "language"):
            if k in fields:
                setattr(doc, k, fields[k])
        if body_changed:
            # Delete old chunks + re-create
            await session.execute(
                _t("DELETE FROM cc_knowledge_chunks WHERE document_id = :d"),
                {"d": doc_id},
            )
            chunks = _simple_chunk(doc.body or "")
            for i, ch in enumerate(chunks):
                session.add(
                    CCKnowledgeChunk(
                        document_id=doc.id, position=i, text_body=ch,
                        text_hash=hashlib.sha256(ch.encode("utf-8")).hexdigest(),
                        token_count=len(ch) // 4,
                    )
                )
            doc.chunk_count = len(chunks)
            doc.embedding_model = None
            doc.embedding_dim = None
            doc.indexed_at = datetime.now(timezone.utc)
        doc.updated_at = datetime.now(timezone.utc)
        await record_audit(
            actor=principal,
            action="customer_care.kb.updated",
            resource_type="cc_knowledge_documents",
            resource_id=doc_id,
            metadata={"fields": list(fields.keys()), "body_changed": body_changed},
        )
    return {"id": str(doc_id), "body_changed": body_changed, "fields": list(fields.keys())}


# ============================================================== Conversation tagging
class TagsPatch(StrictModel):
    tags: list[str] = Field(default_factory=list, max_length=20)


@router.patch(
    "/conversations/{conv_id}/tags",
    summary="Set conversation tags (replaces the list — pass empty list to clear)",
    dependencies=[Depends(requires_permission(_AGENT))],
)
async def patch_conversation_tags(
    conv_id: Annotated[UUID, Path(...)],
    body: TagsPatch,
    uow: Annotated[UnitOfWork, Depends(get_uow)],
    principal: Annotated[Principal, Depends(get_current_principal)],
) -> dict[str, Any]:
    normalized = sorted({t.strip().lower()[:64] for t in body.tags if t.strip()})
    async with uow.transactional() as session:
        await session.execute(
            _t(
                "UPDATE cc_conversations SET tags = :tags, updated_at = now() "
                "WHERE id = :cid"
            ),
            {"tags": normalized or None, "cid": conv_id},
        )
        await record_audit(
            actor=principal,
            action="customer_care.conversation.tagged",
            resource_type="cc_conversation", resource_id=conv_id,
            metadata={"tags": normalized},
        )
    return {"id": str(conv_id), "tags": normalized}


# Route path moved out of /conversations/* namespace to avoid colliding
# with the /conversations/{conv_id} UUID-path matcher in the main router.
@router.get(
    "/tagged-conversations",
    summary="List conversations matching a tag",
    dependencies=[Depends(requires_permission(_AGENT))],
)
async def list_conversations_by_tag(
    uow: Annotated[UnitOfWork, Depends(get_uow)],
    tag: str = Query(..., min_length=1, max_length=64),
    limit: int = Query(default=50, ge=1, le=200),
) -> list[dict[str, Any]]:
    async with uow.transactional() as session:
        rows = (
            await session.execute(
                _t(
                    "SELECT id, customer_id, status, last_message, last_message_at, tags "
                    "FROM cc_conversations WHERE :tag = ANY(tags) "
                    "ORDER BY last_message_at DESC LIMIT :lim"
                ),
                {"tag": tag.strip().lower(), "lim": limit},
            )
        ).all()
        return [
            {
                "id": str(r[0]), "customer_id": str(r[1]),
                "status": r[2], "last_message": r[3],
                "last_message_at": r[4], "tags": r[5] or [],
            }
            for r in rows
        ]


# ============================================================== Saved replies
class SavedReplyCreate(StrictModel):
    title: str = Field(..., min_length=1, max_length=120)
    body: str = Field(..., min_length=1, max_length=4096)
    language: str | None = Field(default=None, max_length=8)
    is_shared: bool = False


class SavedReplyUpdate(StrictModel):
    title: str | None = Field(default=None, min_length=1, max_length=120)
    body: str | None = Field(default=None, min_length=1, max_length=4096)
    language: str | None = Field(default=None, max_length=8)
    is_shared: bool | None = None


@router.post(
    "/saved-replies",
    status_code=201,
    summary="Create a saved reply (quick-text macro) — private to me unless is_shared=true",
    dependencies=[Depends(requires_permission(_AGENT))],
)
async def saved_reply_create(
    body: SavedReplyCreate,
    uow: Annotated[UnitOfWork, Depends(get_uow)],
    principal: Annotated[Principal, Depends(get_current_principal)],
) -> dict[str, Any]:
    async with uow.transactional() as session:
        r = await session.execute(
            _t(
                "INSERT INTO cc_saved_replies (id, owner_user_id, title, body, language, is_shared) "
                "VALUES (gen_random_uuid(), :uid, :t, :b, :l, :s) RETURNING id"
            ),
            {
                "uid": principal.user_id, "t": body.title, "b": body.body,
                "l": body.language, "s": body.is_shared,
            },
        )
        new_id = r.scalar_one()
    return {"id": str(new_id), **body.model_dump()}


@router.get(
    "/saved-replies",
    summary="List my saved replies + shared ones",
    dependencies=[Depends(requires_permission(_AGENT))],
)
async def saved_replies_list(
    uow: Annotated[UnitOfWork, Depends(get_uow)],
    principal: Annotated[Principal, Depends(get_current_principal)],
    limit: int = Query(default=100, ge=1, le=500),
) -> list[dict[str, Any]]:
    async with uow.transactional() as session:
        rows = (
            await session.execute(
                _t(
                    "SELECT id, owner_user_id, title, body, language, is_shared, use_count, created_at "
                    "FROM cc_saved_replies "
                    "WHERE owner_user_id = :uid OR is_shared = true "
                    "ORDER BY use_count DESC, created_at DESC LIMIT :lim"
                ),
                {"uid": principal.user_id, "lim": limit},
            )
        ).all()
        return [
            {
                "id": str(r[0]),
                "owner_user_id": str(r[1]) if r[1] else None,
                "title": r[2], "body": r[3], "language": r[4],
                "is_shared": r[5], "use_count": r[6], "created_at": r[7],
            }
            for r in rows
        ]


@router.patch(
    "/saved-replies/{rid}",
    dependencies=[Depends(requires_permission(_AGENT))],
)
async def saved_reply_update(
    rid: Annotated[UUID, Path(...)],
    body: SavedReplyUpdate,
    uow: Annotated[UnitOfWork, Depends(get_uow)],
    principal: Annotated[Principal, Depends(get_current_principal)],
) -> dict[str, Any]:
    fields = body.model_dump(exclude_none=True)
    if not fields:
        raise ValidationError("nothing to update")
    set_clauses = ", ".join(f"{k} = :{k}" for k in fields)
    params = {**fields, "rid": rid, "uid": principal.user_id}
    async with uow.transactional() as session:
        r = await session.execute(
            _t(
                f"UPDATE cc_saved_replies SET {set_clauses}, updated_at = now() "
                f"WHERE id = :rid AND (owner_user_id = :uid OR is_shared = true) "
                f"RETURNING id"
            ),
            params,
        )
        if r.first() is None:
            raise NotFoundError("Saved reply not found / not yours")
    return {"id": str(rid), **fields}


@router.delete(
    "/saved-replies/{rid}",
    dependencies=[Depends(requires_permission(_AGENT))],
)
async def saved_reply_delete(
    rid: Annotated[UUID, Path(...)],
    uow: Annotated[UnitOfWork, Depends(get_uow)],
    principal: Annotated[Principal, Depends(get_current_principal)],
) -> dict[str, Any]:
    async with uow.transactional() as session:
        r = await session.execute(
            _t(
                "DELETE FROM cc_saved_replies "
                "WHERE id = :rid AND owner_user_id = :uid RETURNING id"
            ),
            {"rid": rid, "uid": principal.user_id},
        )
        if r.first() is None:
            raise NotFoundError("Not found / not yours")
    return {"id": str(rid), "deleted": True}


# ============================================================== Full-text message search
@router.get(
    "/messages/search",
    summary="Trigram-indexed full-text search across messages (ILIKE-based)",
    dependencies=[Depends(requires_permission(_AGENT))],
)
async def messages_search(
    uow: Annotated[UnitOfWork, Depends(get_uow)],
    q: str = Query(..., min_length=2, max_length=200),
    limit: int = Query(default=30, ge=1, le=100),
) -> list[dict[str, Any]]:
    async with uow.transactional() as session:
        rows = (
            await session.execute(
                _t(
                    "SELECT m.id, m.conversation_id, m.sender_type, "
                    "       LEFT(m.message_body, 240), m.created_at, "
                    "       u.full_name, u.phone "
                    "FROM cc_messages m "
                    "JOIN cc_conversations c ON c.id = m.conversation_id "
                    "JOIN users u ON u.id = c.customer_id "
                    "WHERE m.message_body ILIKE :pat "
                    "ORDER BY m.created_at DESC LIMIT :lim"
                ),
                {"pat": f"%{q}%", "lim": limit},
            )
        ).all()
        return [
            {
                "message_id": str(r[0]), "conversation_id": str(r[1]),
                "sender_type": r[2], "preview": r[3],
                "created_at": r[4], "customer_name": r[5],
                "customer_phone": r[6],
            }
            for r in rows
        ]


# ============================================================== Customer notes
class CustomerNoteCreate(StrictModel):
    body: str = Field(..., min_length=1, max_length=4096)
    pinned: bool = False


@router.post(
    "/customers/{customer_id}/notes",
    status_code=201,
    summary="Add an internal agent note on a customer (not visible to customer)",
    dependencies=[Depends(requires_permission(_AGENT))],
)
async def add_customer_note(
    customer_id: Annotated[UUID, Path(...)],
    body: CustomerNoteCreate,
    uow: Annotated[UnitOfWork, Depends(get_uow)],
    principal: Annotated[Principal, Depends(get_current_principal)],
) -> dict[str, Any]:
    async with uow.transactional() as session:
        r = await session.execute(
            _t(
                "INSERT INTO cc_customer_notes (id, customer_id, author_user_id, body, pinned) "
                "VALUES (gen_random_uuid(), :c, :a, :b, :p) RETURNING id, created_at"
            ),
            {"c": customer_id, "a": principal.user_id, "b": body.body, "p": body.pinned},
        )
        row = r.first()
    return {
        "id": str(row[0]), "customer_id": str(customer_id),
        "body": body.body, "pinned": body.pinned, "created_at": row[1],
    }


@router.get(
    "/customers/{customer_id}/notes",
    summary="List agent notes on a customer (pinned first, then newest)",
    dependencies=[Depends(requires_permission(_AGENT))],
)
async def list_customer_notes(
    customer_id: Annotated[UUID, Path(...)],
    uow: Annotated[UnitOfWork, Depends(get_uow)],
) -> list[dict[str, Any]]:
    async with uow.transactional() as session:
        rows = (
            await session.execute(
                _t(
                    "SELECT n.id, n.body, n.pinned, n.created_at, "
                    "       u.full_name AS author_name "
                    "FROM cc_customer_notes n "
                    "LEFT JOIN users u ON u.id = n.author_user_id "
                    "WHERE n.customer_id = :c "
                    "ORDER BY n.pinned DESC, n.created_at DESC LIMIT 50"
                ),
                {"c": customer_id},
            )
        ).all()
        return [
            {
                "id": str(r[0]), "body": r[1], "pinned": r[2],
                "created_at": r[3], "author_name": r[4],
            }
            for r in rows
        ]


# ============================================================== Customer 360
@router.get(
    "/customers/{customer_id}/360",
    summary="Aggregator: customer + recent orders + returns + CSAT + recent conversations",
    dependencies=[Depends(requires_permission(_AGENT))],
)
async def customer_360(
    customer_id: Annotated[UUID, Path(...)],
    uow: Annotated[UnitOfWork, Depends(get_uow)],
) -> dict[str, Any]:
    async with uow.transactional() as session:
        # Base user + cc profile
        u = (
            await session.execute(
                _t(
                    "SELECT u.id, u.email::text, u.phone, u.full_name, u.created_at, "
                    "       p.preferred_language, p.consent_status, p.last_interest "
                    "FROM users u "
                    "LEFT JOIN cc_customer_profile p ON p.customer_id = u.id "
                    "WHERE u.id = :cid"
                ),
                {"cid": customer_id},
            )
        ).first()
        if u is None:
            raise NotFoundError("Customer not found")
        # Recent orders + lifetime value
        orders = (
            await session.execute(
                _t(
                    "SELECT id, code, status, grand_total, placed_at "
                    "FROM orders WHERE customer_user_id = :cid "
                    "ORDER BY placed_at DESC LIMIT 10"
                ),
                {"cid": customer_id},
            )
        ).all()
        lt = (
            await session.execute(
                _t(
                    "SELECT COUNT(*), COALESCE(SUM(grand_total), 0) "
                    "FROM orders WHERE customer_user_id = :cid AND status = 'completed'"
                ),
                {"cid": customer_id},
            )
        ).first()
        # Recent conversations
        convs = (
            await session.execute(
                _t(
                    "SELECT id, status, last_message, last_message_at, handover_required, tags "
                    "FROM cc_conversations WHERE customer_id = :cid "
                    "ORDER BY last_message_at DESC LIMIT 5"
                ),
                {"cid": customer_id},
            )
        ).all()
        # CSAT history
        csat = (
            await session.execute(
                _t(
                    "SELECT score, comment, responded_at FROM cc_csat_surveys "
                    "WHERE customer_id = :cid AND responded_at IS NOT NULL "
                    "ORDER BY responded_at DESC LIMIT 5"
                ),
                {"cid": customer_id},
            )
        ).all()
        notes_cnt = (
            await session.execute(
                _t("SELECT COUNT(*) FROM cc_customer_notes WHERE customer_id = :cid"),
                {"cid": customer_id},
            )
        ).scalar_one()
    return {
        "customer": {
            "id": str(u[0]), "email": u[1], "phone": u[2],
            "full_name": u[3], "joined_at": u[4],
            "preferred_language": u[5], "consent_status": u[6],
            "last_interest": u[7],
        },
        "lifetime": {
            "completed_orders": int(lt[0] or 0),
            "total_spend": str(lt[1] or 0),
        },
        "recent_orders": [
            {
                "id": str(o[0]), "code": o[1], "status": o[2],
                "grand_total": str(o[3]), "placed_at": o[4],
            }
            for o in orders
        ],
        "recent_conversations": [
            {
                "id": str(c[0]), "status": c[1],
                "last_message": c[2], "last_message_at": c[3],
                "handover_required": c[4], "tags": c[5] or [],
            }
            for c in convs
        ],
        "csat_history": [
            {"score": s[0], "comment": s[1], "responded_at": s[2]}
            for s in csat
        ],
        "internal_notes_count": int(notes_cnt or 0),
    }


# ============================================================== After-hours config
def _is_after_hours(now: datetime | None = None) -> bool:
    """Read CC_BUSINESS_HOURS_START / CC_BUSINESS_HOURS_END (e.g. "09:00", "21:00")
    in the operator's local TZ (CC_BUSINESS_TZ_OFFSET hours from UTC,
    default +6 for Bangladesh). Returns True if 'now' is OUTSIDE
    business hours.
    """
    import os
    from datetime import timedelta
    now = now or datetime.now(timezone.utc)
    try:
        start = dtime.fromisoformat(os.environ.get("CC_BUSINESS_HOURS_START") or "09:00")
        end = dtime.fromisoformat(os.environ.get("CC_BUSINESS_HOURS_END") or "21:00")
    except ValueError:
        return False
    offset_hours = int(os.environ.get("CC_BUSINESS_TZ_OFFSET", "6"))
    local = (now + timedelta(hours=offset_hours)).time()
    if start <= end:
        return not (start <= local <= end)
    # Wraps midnight
    return not (local >= start or local <= end)


@router.get(
    "/business-hours",
    summary="Returns current business-hours status + canned after-hours reply text",
    dependencies=[Depends(requires_permission(_AGENT))],
)
async def business_hours_status() -> dict[str, Any]:
    import os
    after = _is_after_hours()
    return {
        "after_hours": after,
        "start": os.environ.get("CC_BUSINESS_HOURS_START") or "09:00",
        "end": os.environ.get("CC_BUSINESS_HOURS_END") or "21:00",
        "tz_offset": int(os.environ.get("CC_BUSINESS_TZ_OFFSET", "6")),
        "auto_reply_bangla": os.environ.get(
            "CC_AFTER_HOURS_REPLY_BN",
            "ধন্যবাদ! আমরা এখন বন্ধ। সকাল ৯টায় আপনার মেসেজের উত্তর দেব।",
        ),
        "auto_reply_english": os.environ.get(
            "CC_AFTER_HOURS_REPLY_EN",
            "Thanks for your message! We're currently closed. We'll reply when we reopen at 9am.",
        ),
    }


# ============================================================== Transcript export (CSV)
@router.get(
    "/conversations/{conv_id}/export",
    summary="Export conversation transcript as CSV / JSON / PDF",
    dependencies=[Depends(requires_permission(_AGENT))],
)
async def export_transcript(
    conv_id: Annotated[UUID, Path(...)],
    uow: Annotated[UnitOfWork, Depends(get_uow)],
    fmt: str = Query(default="csv", pattern=r"^(csv|json|pdf)$"),
) -> StreamingResponse:
    async with uow.transactional() as session:
        rows = (
            await session.execute(
                _t(
                    "SELECT m.created_at, m.sender_type, m.message_type, "
                    "       COALESCE(m.message_body, ''), COALESCE(m.media_url, '') "
                    "FROM cc_messages m "
                    "WHERE m.conversation_id = :cid "
                    "ORDER BY m.created_at ASC"
                ),
                {"cid": conv_id},
            )
        ).all()
        if not rows:
            raise NotFoundError("Conversation not found or empty")
    if fmt == "json":
        import json as _j
        body = _j.dumps([
            {
                "created_at": r[0].isoformat(),
                "sender_type": r[1], "message_type": r[2],
                "message_body": r[3], "media_url": r[4],
            }
            for r in rows
        ], indent=2)
        return StreamingResponse(
            iter([body]),
            media_type="application/json",
            headers={"Content-Disposition": f"attachment; filename=conv-{conv_id}.json"},
        )
    if fmt == "pdf":
        # PDF generation via reportlab. Renders a simple stacked
        # message list with role-prefixed lines. For richer styling
        # (avatars, message bubbles, dates header) move to a Jinja
        # HTML template + WeasyPrint.
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, PageBreak,
        )
        pdf_buf = io.BytesIO()
        doc = SimpleDocTemplate(
            pdf_buf, pagesize=A4,
            leftMargin=0.6 * inch, rightMargin=0.6 * inch,
            topMargin=0.6 * inch, bottomMargin=0.6 * inch,
            title=f"Conversation {conv_id}",
        )
        styles = getSampleStyleSheet()
        h_style = styles["Heading2"]
        meta_style = ParagraphStyle(
            "meta", parent=styles["BodyText"], fontSize=8, textColor="#888888",
        )
        body_style = styles["BodyText"]
        body_style.spaceAfter = 6
        flow = [
            Paragraph(f"Hypershop · Conversation transcript", h_style),
            Paragraph(f"ID: {conv_id} · Messages: {len(rows)}", meta_style),
            Spacer(1, 0.18 * inch),
        ]
        for r in rows:
            ts = r[0].isoformat()
            sender = r[1].upper()
            kind = r[2]
            text = (r[3] or "").replace("<", "&lt;").replace(">", "&gt;")
            label = f"<b>[{sender}]</b> <font color='#888888'>{ts} · {kind}</font>"
            flow.append(Paragraph(label, meta_style))
            flow.append(Paragraph(text or "<i>(empty)</i>", body_style))
            if r[4]:
                flow.append(Paragraph(
                    f"<i>media:</i> {r[4]}", meta_style,
                ))
            flow.append(Spacer(1, 0.06 * inch))
        doc.build(flow)
        pdf_bytes = pdf_buf.getvalue()
        return StreamingResponse(
            iter([pdf_bytes]),
            media_type="application/pdf",
            headers={"Content-Disposition": f"attachment; filename=conv-{conv_id}.pdf"},
        )
    # CSV
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(["timestamp", "sender", "type", "body", "media_url"])
    for r in rows:
        w.writerow([r[0].isoformat(), r[1], r[2], r[3], r[4]])
    return StreamingResponse(
        iter([buf.getvalue()]),
        media_type="text/csv",
        headers={"Content-Disposition": f"attachment; filename=conv-{conv_id}.csv"},
    )


# ============================================================== Meta template-status check
@router.get(
    "/integrations/templates",
    summary="List Meta-approved WhatsApp templates for this WABA",
    dependencies=[Depends(requires_permission(_ADMIN))],
)
async def list_meta_templates() -> dict[str, Any]:
    """Hits Meta Graph API to enumerate approved templates. Returns
    empty list + reason if creds missing.
    """
    import os
    import httpx
    cfg = cc_settings()
    waba_id = os.environ.get("WHATSAPP_WABA_ID")
    if not (cfg.whatsapp_access_token and waba_id):
        return {
            "ok": False,
            "reason": "missing WHATSAPP_ACCESS_TOKEN or WHATSAPP_WABA_ID",
            "templates": [],
        }
    url = f"https://graph.facebook.com/{cfg.whatsapp_api_version}/{waba_id}/message_templates"
    try:
        async with httpx.AsyncClient(timeout=15.0) as client:
            r = await client.get(
                url, headers={"Authorization": f"Bearer {cfg.whatsapp_access_token}"},
            )
            r.raise_for_status()
            data = r.json().get("data") or []
            return {
                "ok": True,
                "templates": [
                    {
                        "name": t.get("name"),
                        "status": t.get("status"),
                        "language": t.get("language"),
                        "category": t.get("category"),
                    }
                    for t in data
                ],
            }
    except httpx.HTTPError as e:
        return {"ok": False, "reason": f"meta_api_error: {e}", "templates": []}


# ============================================================== SLA pause / resume
class SlaPauseRequest(StrictModel):
    reason: str = Field(..., min_length=1, max_length=500)


@router.post(
    "/conversations/{conv_id}/sla/pause",
    summary="Pause SLA timers (e.g. waiting on customer for info)",
    dependencies=[Depends(requires_permission(_AGENT))],
)
async def sla_pause(
    conv_id: Annotated[UUID, Path(...)],
    body: SlaPauseRequest,
    uow: Annotated[UnitOfWork, Depends(get_uow)],
    principal: Annotated[Principal, Depends(get_current_principal)],
) -> dict[str, Any]:
    async with uow.transactional() as session:
        r = await session.execute(
            _t(
                "UPDATE cc_conversations SET sla_paused_at = now(), sla_paused_reason = :r "
                "WHERE id = :c AND sla_paused_at IS NULL RETURNING id"
            ),
            {"c": conv_id, "r": body.reason},
        )
        if r.first() is None:
            raise HTTPException(404, "Conversation not found or already paused")
        await record_audit(
            actor=principal,
            action="customer_care.sla.paused",
            resource_type="cc_conversation", resource_id=conv_id,
            metadata={"reason": body.reason},
        )
    return {"id": str(conv_id), "sla_paused": True, "reason": body.reason}


@router.post(
    "/conversations/{conv_id}/sla/resume",
    summary="Resume SLA timers + shift due dates by paused duration",
    dependencies=[Depends(requires_permission(_AGENT))],
)
async def sla_resume(
    conv_id: Annotated[UUID, Path(...)],
    uow: Annotated[UnitOfWork, Depends(get_uow)],
    principal: Annotated[Principal, Depends(get_current_principal)],
) -> dict[str, Any]:
    """Shifts both due dates forward by (now - sla_paused_at) so the
    agent gets full remaining time after resume."""
    async with uow.transactional() as session:
        r = await session.execute(
            _t(
                "UPDATE cc_conversations "
                "SET sla_first_response_due_at = "
                "      CASE WHEN sla_first_response_due_at IS NOT NULL THEN "
                "           sla_first_response_due_at + (now() - sla_paused_at) "
                "      ELSE NULL END, "
                "    sla_resolution_due_at = "
                "      CASE WHEN sla_resolution_due_at IS NOT NULL THEN "
                "           sla_resolution_due_at + (now() - sla_paused_at) "
                "      ELSE NULL END, "
                "    sla_paused_at = NULL, "
                "    sla_paused_reason = NULL "
                "WHERE id = :c AND sla_paused_at IS NOT NULL RETURNING id"
            ),
            {"c": conv_id},
        )
        if r.first() is None:
            raise HTTPException(404, "Conversation not found or not paused")
        await record_audit(
            actor=principal,
            action="customer_care.sla.resumed",
            resource_type="cc_conversation", resource_id=conv_id,
        )
    return {"id": str(conv_id), "sla_paused": False}


# ============================================================== Per-agent rate limit
_agent_rate_buckets: dict[str, deque] = {}
import os as _os
_AGENT_RATE_LIMIT = int(_os.environ.get("CC_AGENT_RATE_LIMIT_PER_MIN", "120"))


def agent_rate_check(agent_id: UUID) -> tuple[bool, int]:
    """Used by router.send_message — returns (allowed, count_in_window)."""
    now = time.monotonic()
    window_start = now - 60.0
    key = str(agent_id)
    q = _agent_rate_buckets.setdefault(key, deque(maxlen=_AGENT_RATE_LIMIT * 2))
    while q and q[0] < window_start:
        q.popleft()
    if len(q) >= _AGENT_RATE_LIMIT:
        return False, len(q)
    q.append(now)
    return True, len(q) + 1


@router.get(
    "/me/rate-limit",
    summary="Inspect my current rate-limit bucket usage",
    dependencies=[Depends(requires_permission(_AGENT))],
)
async def my_rate_limit(
    principal: Annotated[Principal, Depends(get_current_principal)],
) -> dict[str, Any]:
    key = str(principal.user_id)
    q = _agent_rate_buckets.get(key)
    used = len(q) if q else 0
    return {
        "limit_per_min": _AGENT_RATE_LIMIT,
        "used": used,
        "remaining": max(0, _AGENT_RATE_LIMIT - used),
    }


# ============================================================== Supervisor live monitor
@router.get(
    "/supervisor/live",
    summary="Supervisor view: every online agent with their active conversation count + breached convs",
    dependencies=[Depends(requires_permission(_ADMIN))],
)
async def supervisor_live(
    uow: Annotated[UnitOfWork, Depends(get_uow)],
) -> dict[str, Any]:
    async with uow.transactional() as session:
        agents = (
            await session.execute(
                _t(
                    "SELECT u.id, u.email::text, u.full_name, a.status, "
                    "       a.current_active_chats, a.max_active_chats, "
                    "       COUNT(c.id) FILTER (WHERE c.status='open' AND c.agent_id=u.id "
                    "                            AND (c.sla_first_response_breached "
                    "                                 OR c.sla_resolution_breached)) AS breached "
                    "FROM cc_agent_profile a "
                    "JOIN users u ON u.id = a.user_id "
                    "LEFT JOIN cc_conversations c ON c.agent_id = u.id "
                    "GROUP BY u.id, u.email, u.full_name, a.status, "
                    "         a.current_active_chats, a.max_active_chats "
                    "ORDER BY (a.status = 'online') DESC, a.current_active_chats DESC"
                ),
            )
        ).all()
        global_stats = (
            await session.execute(
                _t(
                    "SELECT "
                    "  (SELECT COUNT(*) FROM cc_conversations WHERE status='open') AS open, "
                    "  (SELECT COUNT(*) FROM cc_conversations WHERE status='open' AND agent_id IS NULL) AS unassigned, "
                    "  (SELECT COUNT(*) FROM cc_conversations WHERE status='open' AND handover_required) AS handover, "
                    "  (SELECT COUNT(*) FROM cc_conversations WHERE sla_paused_at IS NOT NULL) AS paused"
                ),
            )
        ).first()
    return {
        "global": {
            "open": int(global_stats[0] or 0),
            "unassigned": int(global_stats[1] or 0),
            "handover": int(global_stats[2] or 0),
            "sla_paused": int(global_stats[3] or 0),
        },
        "agents": [
            {
                "agent_id": str(a[0]), "email": a[1], "name": a[2],
                "status": a[3],
                "current_active_chats": int(a[4]),
                "max_active_chats": int(a[5]),
                "breached_open_convs": int(a[6] or 0),
            }
            for a in agents
        ],
    }
