-- ============================================================================
-- seed_gap_admin_lite.sql
--
-- Idempotent backing data for the admin-lite "Security & access" console
-- (AdminLiteClient.tsx) so its three GET gap endpoints return REAL rows:
--
--   GET /admin/admin-lite/ip-allowlist            -> ip_allowlist_entries
--   GET /admin/admin-lite/rbac/grants/{role_code} -> rbac_role_grants
--   GET /admin/admin-lite/alerts                  -> security_alerts
--
-- The security-hardening pack does NOT ship these tables in this build, so the
-- read endpoints fall back to an empty list. This script creates each table
-- (IF NOT EXISTS) with the EXACT columns the GETs SELECT (every GET does
-- `SELECT * ... ORDER BY id DESC`, and alerts rows are read by
-- id/severity/status/created_at), plus the columns the action endpoints
-- INSERT/UPDATE, then seeds realistic Bangladeshi demo rows.
--
-- Pure Postgres. Safe to run repeatedly (CREATE TABLE IF NOT EXISTS +
-- INSERT ... ON CONFLICT DO NOTHING). gen_random_uuid()/now() are fine.
-- ============================================================================

-- ── IP allowlist ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ip_allowlist_entries (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope       text        NOT NULL DEFAULT 'admin',
    label       text        NOT NULL,
    cidr        text        NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_ip_allowlist_scope_cidr UNIQUE (scope, cidr)
);

INSERT INTO ip_allowlist_entries (scope, label, cidr) VALUES
    ('admin', 'Dhaka HQ office (Gulshan)',        '103.230.104.0/24'),
    ('admin', 'Chattogram warehouse uplink',      '203.112.218.0/25'),
    ('role',  'Finance team VPN egress',          '103.197.205.16/28'),
    ('user',  'On-call ops (Banani residence)',   '118.179.140.55/32'),
    ('admin', 'Sylhet support desk',              '114.130.54.0/26'),
    ('admin', 'Cloud bastion (Singapore region)', '13.228.0.0/15')
ON CONFLICT (scope, cidr) DO NOTHING;

-- ── RBAC role grants ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS rbac_role_grants (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code   text        NOT NULL,
    scope_code  text        NOT NULL,
    conditions  jsonb,
    note        text,
    created_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_rbac_role_scope UNIQUE (role_code, scope_code)
);

INSERT INTO rbac_role_grants (role_code, scope_code, conditions, note) VALUES
    ('admin',           'payment.refund',        '{"amount_lte": 50000}'::jsonb, 'Refunds up to 500 BDT'),
    ('admin',           'catalog.product.write', NULL,                            'Full catalog edit'),
    ('order_manager',   'order.cancel',          '{"within_hours": 24}'::jsonb,   'Cancel within 24h'),
    ('finance_manager', 'payout.approve',        '{"amount_lte": 1000000}'::jsonb,'Payouts up to 10,000 BDT'),
    ('risk_officer',    'fraud_analytics.view',  NULL,                            'Read-only fraud dash'),
    ('warehouse_manager','inventory.break_pack', NULL,                            'Break-pack at DC')
ON CONFLICT (role_code, scope_code) DO NOTHING;

-- ── Security alerts inbox ───────────────────────────────────────────────────
-- GET reads id / severity / status / created_at; action UPDATEs status.
CREATE TABLE IF NOT EXISTS security_alerts (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    severity    text        NOT NULL DEFAULT 'info',
    status      text        NOT NULL DEFAULT 'open',
    title       text,
    source      text,
    created_at  timestamptz NOT NULL DEFAULT now()
);

INSERT INTO security_alerts (severity, status, title, source, created_at) VALUES
    ('critical', 'open',      'Repeated failed admin logins from 45.119.0.0/16', 'auth_guard',    now() - interval '20 minutes'),
    ('high',     'open',      'COD ledger hash-chain verify lag > 5 min',         'cod_ledger',    now() - interval '2 hours'),
    ('high',     'acknowledged','Bulk export of seller PII by data_analyst',      'dlp_scanner',   now() - interval '6 hours'),
    ('warning',  'open',      'TLS cert for api.hypershop.com.bd expires in 14d', 'tls_monitor',   now() - interval '1 day'),
    ('warning',  'snoozed',   'New device login for admin (Cox''s Bazar)',        'device_guard',  now() - interval '2 days'),
    ('info',     'resolved',  'Nightly pg_dump to R2 completed',                  'backup_cron',   now() - interval '8 hours'),
    ('info',     'open',      'Feature flag toggled: sponsored_brands_v2',        'feature_flags', now() - interval '3 hours')
ON CONFLICT DO NOTHING;
