"""Offline bulk SEO generator for a Daraz-style item xlsx.

Usage:
    .venv/Scripts/python -m scripts.seo_bulk_from_xlsx \
        --in  "C:/path/Daraz_Style_10k_SEO_Items.xlsx" \
        --out "C:/path/Daraz_Style_10k_SEO_Items.with_seo.xlsx"

Reads the 10k-row workbook (sheet ``10k_Database``) and writes a new
workbook with 9 SEO columns appended per row:

    slug, canonical_url,
    meta_title_en, meta_desc_en, meta_keywords_en,
    meta_title_bn, meta_desc_bn, meta_keywords_bn,
    jsonld_product

The SEO meta is generated by the same ``build_product_seo`` pure
builder that the live auto-SEO engine uses on product activate, so the
output here is byte-equivalent to what the engine would write into
the DB if these rows were ingested into the catalog.

JSON-LD is a compact, single-line Product schema string ready to inject
into the PDP head — same shape as ``app/modules/seo/builders.py:productJsonLd``
emits, but built offline since we have no DB row to attach to.

No backend, no DB, no network — purely a file-in / file-out tool so the
operator can run it any time without spinning up Postgres.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

import openpyxl

# Reuse the same pure builder the live engine uses on product activate.
# Keeps the offline output 1:1 with what the DB ingest path would write.
from app.modules.seo.autogen import build_product_seo


_SITE_BASE = "https://hypershop.com.bd"
_SHEET_NAME = "10k_Database"
_HEADER_ROW = (
    "SKU", "Category", "Brand", "Core Product", "Specification",
    "Stock Status", "Estimated Price (BDT)", "SEO Optimized Title",
)
_NEW_COLS = (
    "slug", "canonical_url",
    "meta_title_en", "meta_desc_en", "meta_keywords_en",
    "meta_title_bn", "meta_desc_bn", "meta_keywords_bn",
    "jsonld_product",
)


def slugify(text: str) -> str:
    """ASCII-safe slug. Falls back to SKU if name is empty."""
    text = (text or "").lower().strip()
    text = re.sub(r"[^a-z0-9\s-]", "", text)
    text = re.sub(r"\s+", "-", text)
    text = re.sub(r"-+", "-", text).strip("-")
    return text[:80]


def stock_to_availability(stock: str) -> str:
    """Map the xlsx Stock Status column to schema.org Availability values."""
    s = (stock or "").strip().lower()
    if s in ("in stock", "available"):
        return "https://schema.org/InStock"
    if s in ("low stock", "limited"):
        return "https://schema.org/LimitedAvailability"
    if s in ("out of stock", "sold out"):
        return "https://schema.org/OutOfStock"
    return "https://schema.org/InStock"


def build_jsonld(
    *,
    sku: str,
    name: str,
    brand: str | None,
    category: str | None,
    description: str,
    price_minor: int,
    availability: str,
    url: str,
) -> str:
    """Compact Product JSON-LD ready to drop into the PDP head."""
    obj: dict[str, Any] = {
        "@context": "https://schema.org",
        "@type": "Product",
        "name": name,
        "sku": sku,
        "description": description,
        "url": url,
        "offers": {
            "@type": "Offer",
            "price": f"{price_minor / 100:.2f}",
            "priceCurrency": "BDT",
            "availability": availability,
            "url": url,
            "seller": {"@type": "Organization", "name": "Hypershop BD"},
        },
    }
    if brand:
        obj["brand"] = {"@type": "Brand", "name": brand}
    if category:
        obj["category"] = category
    return json.dumps(obj, ensure_ascii=False, separators=(",", ":"))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--in", dest="in_path", required=True,
                        help="Input xlsx path")
    parser.add_argument("--out", dest="out_path", required=True,
                        help="Output xlsx path")
    parser.add_argument("--site-base", default=_SITE_BASE,
                        help=f"Site base for canonical URLs (default {_SITE_BASE})")
    parser.add_argument("--limit", type=int, default=0,
                        help="Process only first N rows (0 = all)")
    args = parser.parse_args()

    in_path = Path(args.in_path)
    out_path = Path(args.out_path)
    if not in_path.exists():
        print(f"input not found: {in_path}", file=sys.stderr)
        return 2

    print(f"reading: {in_path}")
    wb_in = openpyxl.load_workbook(in_path, read_only=True, data_only=True)
    if _SHEET_NAME not in wb_in.sheetnames:
        print(f"sheet {_SHEET_NAME!r} not found; available: "
              f"{wb_in.sheetnames}", file=sys.stderr)
        return 2
    ws_in = wb_in[_SHEET_NAME]

    rows_iter = ws_in.iter_rows(values_only=True)
    header = next(rows_iter)
    if tuple(str(c or "") for c in header[: len(_HEADER_ROW)]) != _HEADER_ROW:
        print(f"WARN: header mismatch. got: {header}", file=sys.stderr)
        # Proceed anyway — column order matters more than header text.

    wb_out = openpyxl.Workbook(write_only=True)
    ws_out = wb_out.create_sheet(title="10k_Database_with_seo")
    ws_out.append(list(_HEADER_ROW) + list(_NEW_COLS))

    seen_slugs: dict[str, int] = {}
    n_written = 0
    n_skipped = 0
    for idx, row in enumerate(rows_iter, start=1):
        if args.limit and n_written >= args.limit:
            break
        try:
            sku = str(row[0] or "").strip()
            category = str(row[1] or "").strip()
            brand = str(row[2] or "").strip()
            core = str(row[3] or "").strip()
            spec = str(row[4] or "").strip()
            stock = str(row[5] or "").strip()
            price_bdt = row[6]
            seo_title_seed = str(row[7] or "").strip()

            if not sku or not core:
                n_skipped += 1
                continue

            # Build name. The xlsx already carries a coarse "SEO Optimized
            # Title" — we prefer that for the human-readable name when it's
            # meaningful, falling back to Brand + Core Product.
            display_name = (
                seo_title_seed
                if seo_title_seed and len(seo_title_seed) >= len(core)
                else f"{brand} {core}".strip() or core
            )

            # ---- slug + canonical URL ----
            base_slug = slugify(display_name) or slugify(sku.lower())
            n = seen_slugs.get(base_slug, 0)
            slug = base_slug if n == 0 else f"{base_slug}-{n + 1}"
            seen_slugs[base_slug] = n + 1
            canonical_url = f"{args.site_base.rstrip('/')}/product/{slug}"

            # ---- SEO meta via the live engine builder ----
            seo = build_product_seo(
                name=display_name,
                brand=brand or None,
                category=category or None,
                short_description=spec or None,
            )

            # ---- JSON-LD (price in minor, schema.org Offer) ----
            try:
                price_minor = int(round(float(price_bdt or 0) * 100))
            except (TypeError, ValueError):
                price_minor = 0
            jsonld = build_jsonld(
                sku=sku,
                name=display_name,
                brand=brand or None,
                category=category or None,
                description=seo["en"]["description"],
                price_minor=price_minor,
                availability=stock_to_availability(stock),
                url=canonical_url,
            )

            ws_out.append([
                sku, category, brand, core, spec, stock, price_bdt,
                seo_title_seed,
                slug, canonical_url,
                seo["en"]["title"],
                seo["en"]["description"],
                seo["en"]["keywords"],
                seo["bn"]["title"],
                seo["bn"]["description"],
                seo["bn"]["keywords"],
                jsonld,
            ])
            n_written += 1
            if n_written % 1000 == 0:
                print(f"  {n_written} rows written...")
        except Exception as exc:  # noqa: BLE001 — per-row soft-fail
            n_skipped += 1
            print(f"  row {idx} skipped: {exc}", file=sys.stderr)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    wb_out.save(out_path)
    print()
    print(f"done. written={n_written} skipped={n_skipped}")
    print(f"output: {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
